// =============================================================================
// ORCHESTRATOR - full deployment: platform + all clients.
// azd uses this file as the entry point (scope: resource group).
// STATIC and client-agnostic: the client list lives in clients.gen.bicep,
// GENERATED by tools/build-facade.py by reading /clients/*/mcp-manifest.yaml.
// =============================================================================
param baseName string
param location string = resourceGroup().location
param publisherEmail string
param publisherName string

@allowed(['native-mcp', 'rest-consumption', 'policy-mcp-consumption'])
param gatewayProfile string = 'native-mcp'

@allowed(['public', 'hybrid', 'isolated'])
param networkProfile string = 'public'
param vnetIntegrationSubnetId string = '' // hybrid: delegated subnet (outbound integration)
param vnetInjectionSubnetId string = ''   // isolated: dedicated subnet (injection)

// Set this to attach to an existing APIM in the same resource group
// instead of creating a new one (see platform.bicep for requirements).
param existingApimName string = ''

// Telemetry: 'new' (the kit creates App Insights, default), 'existing' (reuse
// yours: name + optional RG), 'none' (none). See platform.bicep.
@allowed(['new', 'existing', 'none'])
param telemetryMode string = 'new'
param existingAppInsightsName string = ''
param existingAppInsightsResourceGroup string = ''

// Key Vault purge protection: enable in production (see platform.bicep).
param kvPurgeProtection bool = false

// Identity of the deployer (azd passes it from AZURE_PRINCIPAL_ID via bicepparam):
// gets the role required to write secrets into Key Vault.
param principalId string = ''

// azd environment name (from AZURE_ENV_NAME): azd-env-name tag on created resources.
param azdEnvName string = ''

module platform '../platform/platform.bicep' = {
  name: 'platform'
  params: {
    baseName: baseName
    location: location
    publisherEmail: publisherEmail
    publisherName: publisherName
    gatewayProfile: gatewayProfile
    networkProfile: networkProfile
    vnetIntegrationSubnetId: vnetIntegrationSubnetId
    vnetInjectionSubnetId: vnetInjectionSubnetId
    existingApimName: existingApimName
    telemetryMode: telemetryMode
    existingAppInsightsName: existingAppInsightsName
    existingAppInsightsResourceGroup: existingAppInsightsResourceGroup
    kvPurgeProtection: kvPurgeProtection
    deployerPrincipalId: principalId
    azdEnvName: azdEnvName
  }
}

module clients './clients.gen.bicep' = {
  name: 'clients'
  params: {
    apimName: platform.outputs.apimName
    keyVaultName: platform.outputs.keyVaultName
    enableNativeMcp: platform.outputs.nativeMcpEnabled
  }
}

module policyMcpClients './policy-mcp-clients.gen.bicep' = {
  name: 'policy-mcp-clients'
  params: {
    apimName: platform.outputs.apimName
    enabled: platform.outputs.policyMcpEnabled
  }
  dependsOn: [clients]
}

output apimName string = platform.outputs.apimName
output apimGatewayUrl string = platform.outputs.apimGatewayUrl
output keyVaultName string = platform.outputs.keyVaultName
output mcpServerUrls object = clients.outputs.mcpServerUrls
output restApiUrls object = clients.outputs.restApiUrls
output policyMcpServerUrls object = policyMcpClients.outputs.serverUrls
